

language: "fr_fr"

# Current server name (used for bungee mode)
server-name: "server"

# Available storage modes:
# - BUNGEE
# - MYSQL
# - SQLITE
storage-mode: BUNGEE


# TODO : separate database configuration in a separate file
# No used if storage-mode is BUNGEE
# If storage-mode is BUNGEE, go to the BungeeCord configuration file and edit the database configuration
mysql:
  host: "127.0.0.1"
  port: 3306
  database: "singularity"
  username: "username"
  password: "password"

sqlite:
  file: "singularity.db"
