

language: "fr_fr"

# Available storage modes:
# - "bungee"
# - "mysql"
# - "sqlite"
storage_mode: "bungee"

mysql:
  host: "127.0.0.1"
  port: 3306
  database: "singularity"
  username: "username"
  password: "password"

sqlite:
  file: "singularity.db"
